config/routes.rb
LoneyetiBlog::Application.routes.draw do
  resources :categories

  resources :fiction

  resources :apps

  resources :music

   root :to => 'posts#index'
   get "home" => "home#index"
   get "posts/admin" => "posts#admin"
   get "posts/new"
   post "posts/create"
   get "posts/:id" => "posts#show", :as => :post
   get "posts" => "posts#index"
   get "posts/:id/edit" => "posts#edit"
   put "posts/:id" => "posts#update"
   delete "posts/:id" => "posts#destroy"

end

app/models/fiction.rb
class Fiction < ActiveRecord::Base
  set_table_name 'fiction'
  attr_accessible :description, :externalLink, :imagePath, :name
end

app/controllers/fiction_controller.rb
class FictionController < ApplicationController
  http_basic_authenticate_with :name => "tharris", :password => "d3ltac0", :except => [:index]
  
  # GET /fiction
  # GET /fiction.json
  def index
    @fiction = Fiction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fiction }
    end
  end

  # GET /fiction/1
  # GET /fiction/1.json
  def show
    @fiction = Fiction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fiction }
    end
  end

  # GET /fiction/new
  # GET /fiction/new.json
  def new
    @fiction = Fiction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fiction }
    end
  end

  # GET /fiction/1/edit
  def edit
    @fiction = Fiction.find(params[:id])
  end

  # POST /fiction
  # POST /fiction.json
  def create
    @fiction = Fiction.new(params[:fiction])

    respond_to do |format|
      if @fiction.save
        format.html { redirect_to @fiction, notice: 'Fiction was successfully created.' }
        format.json { render json: @fiction, status: :created, location: @fiction }
      else
        format.html { render action: "new" }
        format.json { render json: @fiction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fiction/1
  # PUT /fiction/1.json
  def update
    @fiction = Fiction.find(params[:id])

    respond_to do |format|
      if @fiction.update_attributes(params[:fiction])
        format.html { redirect_to @fiction, notice: 'Fiction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fiction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fiction/1
  # DELETE /fiction/1.json
  def destroy
    @fiction = Fiction.find(params[:id])
    @fiction.destroy

    respond_to do |format|
      format.html { redirect_to fiction_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fiction_helper.rb
module FictionHelper
end

app/views/fiction/_form.html.erb
<%= form_for(@fiction) do |f| %>
  <% if @fiction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fiction.errors.count, "error") %> prohibited this fiction from being saved:</h2>

      <ul>
      <% @fiction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :imagePath %><br />
    <%= f.text_field :imagePath %>
  </div>
  <div class="field">
    <%= f.label :externalLink %><br />
    <%= f.text_field :externalLink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fiction/edit.html.erb
<h1>Editing fiction</h1>

<%= render 'form' %>

<%= link_to 'Show', @fiction %> |
<%= link_to 'Back', fiction_index_path %>

app/views/fiction/index.html.erb
  <h1 class="pagetitle">fiction</h1>
  <hr class="article" />

<% @fiction.each do |fiction| %>
<div class="projects">

    <img class="rounded-img" src="<%= fiction.imagePath %>"/>
    <h1><a href="<%= fiction.externalLink %>"><%= fiction.name %></a></h1>
    <%= fiction.description.html_safe %>
</div>
<% end %>

app/views/fiction/new.html.erb
<h1>New fiction</h1>

<%= render 'form' %>

<%= link_to 'Back', fiction_index_path %>

app/views/fiction/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @fiction.name %>
</p>

<p>
  <b>Description:</b>
  <%= @fiction.description %>
</p>

<p>
  <b>Imagepath:</b>
  <%= @fiction.imagePath %>
</p>

<p>
  <b>Externallink:</b>
  <%= @fiction.externalLink %>
</p>


<%= link_to 'Edit', edit_fiction_path(@fiction) %> |
<%= link_to 'Back', fiction_index_path %>