config/routes.rb
LoneyetiBlog::Application.routes.draw do
  resources :categories

  resources :fiction

  resources :apps

  resources :music

   root :to => 'posts#index'
   get "home" => "home#index"
   get "posts/admin" => "posts#admin"
   get "posts/new"
   post "posts/create"
   get "posts/:id" => "posts#show", :as => :post
   get "posts" => "posts#index"
   get "posts/:id/edit" => "posts#edit"
   put "posts/:id" => "posts#update"
   delete "posts/:id" => "posts#destroy"

end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :imagePath %><br />
    <%= f.text_field :imagePath %>
  </div>
  <div class="field">
    <%= f.label :externalLink %><br />
    <%= f.text_field :externalLink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
  <h1 class="pagetitle">mobile apps</h1>
  <hr class="article" />

<% @apps.each do |app| %>
<div class="projects">

    <img class="rounded-img" src="<%= app.imagePath %>"/>
    <h1><a href="<%= app.externalLink %>"><%= app.name %></a></h1>
    <%= app.description.html_safe %>
</div>
<% end %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @app.name %>
</p>

<p>
  <b>Description:</b>
  <%= @app.description %>
</p>

<p>
  <b>Imagepath:</b>
  <%= @app.imagePath %>
</p>

<p>
  <b>Externallink:</b>
  <%= @app.externalLink %>
</p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>