config/routes.rb
LoneyetiBlog::Application.routes.draw do
  resources :categories

  resources :fiction

  resources :apps

  resources :music

   root :to => 'posts#index'
   get "home" => "home#index"
   get "posts/admin" => "posts#admin"
   get "posts/new"
   post "posts/create"
   get "posts/:id" => "posts#show", :as => :post
   get "posts" => "posts#index"
   get "posts/:id/edit" => "posts#edit"
   put "posts/:id" => "posts#update"
   delete "posts/:id" => "posts#destroy"

end

app/models/music.rb
class Music < ActiveRecord::Base
  set_table_name 'music'
  attr_accessible :description, :externalLink, :imagePath, :name
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  http_basic_authenticate_with :name => "tharris", :password => "d3ltac0", :except => [:index]

  # GET /music
  # GET /music.json
  def index
    @music = Music.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @music }
    end
  end

  # GET /music/1
  # GET /music/1.json
  def show
    @music = Music.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @music }
    end
  end

  # GET /music/new
  # GET /music/new.json
  def new
    @music = Music.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @music }
    end
  end

  # GET /music/1/edit
  def edit
    @music = Music.find(params[:id])
  end

  # POST /music
  # POST /music.json
  def create
    @music = Music.new(params[:music])

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render json: @music, status: :created, location: @music }
      else
        format.html { render action: "new" }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /music/1
  # PUT /music/1.json
  def update
    @music = Music.find(params[:id])

    respond_to do |format|
      if @music.update_attributes(params[:music])
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /music/1
  # DELETE /music/1.json
  def destroy
    @music = Music.find(params[:id])
    @music.destroy

    respond_to do |format|
      format.html { redirect_to music_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/music_helper.rb
module MusicHelper
end

app/views/music/_form.html.erb
<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :imagePath %><br />
    <%= f.text_field :imagePath %>
  </div>
  <div class="field">
    <%= f.label :externalLink %><br />
    <%= f.text_field :externalLink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/music/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', music_index_path %>

app/views/music/index.html.erb
  <h1 class="pagetitle">music</h1>
  <hr class="article" />

<% @music.each do |music| %>
<div class="projects">

    <img class="rounded-img" src="<%= music.imagePath %>"/>
    <h1><a href="<%= music.externalLink %>"><%= music.name %></a></h1>
    <%= music.description.html_safe %>
</div>
<% end %>
<div id="clear"/>
<br />

app/views/music/new.html.erb
<h1>New music</h1>

<%= render 'form' %>

<%= link_to 'Back', music_index_path %>

app/views/music/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @music.name %>
</p>

<p>
  <b>Description:</b>
  <%= @music.description %>
</p>

<p>
  <b>Imagepath:</b>
  <%= @music.imagePath %>
</p>

<p>
  <b>Externallink:</b>
  <%= @music.externalLink %>
</p>


<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', music_index_path %>