config/routes.rb
LoneyetiBlog::Application.routes.draw do
  resources :categories

  resources :fiction

  resources :apps

  resources :music

   root :to => 'posts#index'
   get "home" => "home#index"
   get "posts/admin" => "posts#admin"
   get "posts/new"
   post "posts/create"
   get "posts/:id" => "posts#show", :as => :post
   get "posts" => "posts#index"
   get "posts/:id/edit" => "posts#edit"
   put "posts/:id" => "posts#update"
   delete "posts/:id" => "posts#destroy"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :posts, :through => :categorizations
    
  attr_accessible :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  http_basic_authenticate_with :name => "tharris", :password => "d3ltac0", :except => [:index, :show]
	
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
    @categories = Category.all(:order => "name")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    @posts = @category.categorizations.posts
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= link_to category.name, category %></td>
  </tr>
<% end %>
</table>

<br />

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

  <h1 class="pagetitle"><%= @category.name %></h1>
  <hr class="article">
    <div class="theloop">
<aside class="sidebar">
   <div class="sidebox">
<iframe width="150" height="295" style="position: relative; display: block; width: 150px; height: 295px;" src="http://bandcamp.com/EmbeddedPlayer/v=2/album=3191637067/size=tall/bgcol=FFFFFF/linkcol=4285BB/transparent=true/" allowtransparency="true" frameborder="0"><a href="http://scenery.bandcamp.com/album/humdrum">Humdrum by Scenery</a></iframe>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-6628809286334311";
/* Lone Yeti #1 */
google_ad_slot = "8280140986";
google_ad_width = 160;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
      <h3>Categories</h3>
      <ul>
        <% @categories.each do |category| %>
          <li><%= link_to category.name, category %></li>
        <% end %>
      </ul>
    </div>
</aside>



   <% @posts.each do |post| %>
    <div class="post">
      <h2 class="title"><%= link_to post.title, post %></h2>
      <span class="date"><%= l post.created_at, :format => :long_datetime %></span>
      <p><%= raw(post.text) %></p>
      <p class="postfoot">
        Posted in:
         <% post.categories.each do |post_category| %>
          <%= link_to post_category.name, post_category %>&nbsp;
        <% end %>
        / Bookmark the <%= link_to "article", post %>
      </p>
    </div>
   <% end %>
</div>



</div>

<%= link_to 'Back', categories_path %>

app/views/categories/showbak.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @category.name %></h1>
    <ul>
   <% @posts.each do |post| %>
       <li>
          <%= link_to post.title, post %>
       </li>
   <% end %>
    </ul>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>